field: 5cfc6611-0ee8-4be7-b408-8a482454093d # Recipe Content
fieldLayouts:
  8d27fe53-2877-471c-818d-1eac4ef7a6cd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7949122a-4ec4-4649-87fd-3c44a2894afa # Ingredients
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f27ceb0-9009-4e4b-a279-1c4de78214c4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e86ee7a9-45e6-4fbf-bc74-1fa0c613104c
        userCondition: null
fields:
  7949122a-4ec4-4649-87fd-3c44a2894afa: # Ingredients
    columnSuffix: tdldcwmt
    contentColumnType: text
    fieldGroup: null
    handle: ingredients
    instructions: null
    name: Ingredients
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Amount
                -
                  - handle
                  - amount
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Ingredient
                -
                  - handle
                  - ingredient
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: recipeIngredients
name: 'Recipe Ingredients'
sortOrder: 5
