field: 5cfc6611-0ee8-4be7-b408-8a482454093d # Recipe Content
fieldLayouts:
  c540c195-1203-4bec-9755-79bb6b3471a1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ed2e75ad-9d3b-4a5a-bee4-fcf4400b3b20 # Tip Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d2325a0-a832-45e1-b790-63922afba61a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d969c46d-a36a-46ec-812c-58e125615924
        userCondition: null
fields:
  ed2e75ad-9d3b-4a5a-bee4-fcf4400b3b20: # Tip Content
    columnSuffix: qtpxevau
    contentColumnType: text
    fieldGroup: null
    handle: tipContent
    instructions: null
    name: 'Tip Content'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeTip
name: 'Recipe Tip'
sortOrder: 2
