field: 5cfc6611-0ee8-4be7-b408-8a482454093d # Recipe Content
fieldLayouts:
  b904fc51-35cb-4ca4-9f3a-34fe726e566a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 58233f1d-189d-446d-9d5b-101f4e168011 # Steps title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 861b0e6b-5f98-49ad-871b-98008a9138e7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: b893b826-1ac0-4dd2-bd4c-1bb49a2a459a # Steps content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82e29177-7018-4a4a-993f-e9afd855924c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cda18446-b730-4a8e-8439-423032936983
        userCondition: null
fields:
  58233f1d-189d-446d-9d5b-101f4e168011: # Steps title
    columnSuffix: fzoozije
    contentColumnType: text
    fieldGroup: null
    handle: stepsTitle
    instructions: null
    name: 'Steps title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b893b826-1ac0-4dd2-bd4c-1bb49a2a459a: # Steps content
    columnSuffix: ppdswkgr
    contentColumnType: text
    fieldGroup: null
    handle: stepsContent
    instructions: null
    name: 'Steps content'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Step Instructions'
                -
                  - handle
                  - stepInstructions
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: null
      minRows: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: recipeSteps
name: 'Recipe Steps'
sortOrder: 4
