fieldLayouts:
  4bab0fac-3a4b-4229-a38c-9f972aff01d7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: 'Homepage title'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 687fdb47-d874-482b-ae72-94d1e05c0c87
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d29dc04-ed53-4439-9535-4f5bcada9026 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d0eadbe1-fb8b-47c6-9c7e-38f81bf85fac
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1d505816-48f0-4f5f-827a-28d2a1dc6d87
        userCondition: null
handle: homepage
hasTitleField: true
name: Homepage
section: cad843b7-9bbd-4723-8d15-3bb95dd889a8 # Homepage
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
