fieldLayouts:
  be79e37c-92c2-471d-91e0-b6032b2d6baa:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: dc8f7828-e395-4491-b1fb-415fda886303
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 381beaba-7e5a-4b44-8d99-61abe2fcf56d
        userCondition: null
fs: local
handle: news
name: News
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
