columnSuffix: null
contentColumnType: string
fieldGroup: fd6bb182-461e-40ca-a7d4-0555853978ce # Drinks
handle: drinkRecipe
instructions: null
name: 'Drink Recipe'
searchable: false
settings:
  allowSelfRelations: false
  localizeRelations: false
  maxRelations: 1
  minRelations: 1
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: 'Add a drink recipe'
  showSiteMenu: false
  source: null
  sources:
    - 'section:4edb9df3-63d5-4187-a6d4-1d054b288a6a' # Recipes
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
