columnSuffix: uuxioygr
contentColumnType: text
fieldGroup: fd6bb182-461e-40ca-a7d4-0555853978ce # Drinks
handle: introduction
instructions: 'Short sentence at top of drinks page.'
name: Introduction
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
