defaultPlacement: end
enableVersioning: true
handle: aboutCraftyCoffee
name: 'About Crafty Coffee'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9cb4da37-9508-49e4-b376-f5fb14a07b70: # Craft
    enabledByDefault: true
    hasUrls: true
    template: about/_entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 3b35800e-a640-4ac1-8972-44a82788bdf4
type: structure
